# background colour
background #000000
# text colour
foreground #ffffff
# background
background_opacity 0.475
# close without asking
confirm_os_window_close 0
# font
font_family AdwaitaMono Nerd Font
